name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Build React App
        run: npm run build
        working-directory: frontend

      - name: Build Electron EXE
        run: npm run dist
        working-directory: frontend

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: RCL-BMS-EXE
          path: frontend/release/